### ISSUE TITLE
Is the inheritance of IClient necessary in ChiefDriver?

### ISSUE THREAD

**Issue by taeguk** [samchon/framework#3]
https://github.com/samchon/framework/blob/b3d69bcd857412140fd401e47ecf8366d2dab73b/cpp/samchon/example/interaction/ChiefDriver.hpp#L48

Is the inheritance of IClient necessary?
From what I understand is, the ChiefDriver is a only server.

**Comment by samchon** [comment]
Yes, it is essential.
http://samchon.github.io/framework/api/cpp/d3/dc8/classsamchon_1_1protocol_1_1IClient.html

#### IServer and IClient
*IServer* is a class for opening a server and accepting clients. But it doesn't have any function communicating with clients. *IClient* is a class having functions for network communication (network message I/O).
  - In server side, *IClient* means a driver for each client who connected with the server.
    - IClient is constructed in *IServer::addClient*.
  - In client side, *IClient* means itself with *ServerConnector*.

#### ChiefDriver
**ChiefDriver** is a 1:1 server accepts only a chief system. Unlike ordinary server accecpting many clients, it only accepts a client. So I think separating accepting clients (*IServer*) and driver handling each client (*IClient*) is not required.

http://samchon.github.io/framework/api/cpp/d4/dde/classsamchon_1_1example_1_1interaction_1_1ChiefDriver.html

That's the reason why **ChiefDriver** inherits *IServer* and *IClient* at the same time.

**Comment by taeguk** [comment]
Ah! Thanks, I understand :)

**Comment by samchon** [comment]
@taeguk Thanks for your sugguestion and contribution.

Your idea is the best. I will adopt your sugguestion, but something will be changed for JavaScript. As you know, **multiple and virtual inheritances** are only possible in C\++. I want C++ and JavaScript share same architecture design. Make the design to be compatible, I've to change your solution.

#### New Design
The next design will form like below:
  - Keeping right notation.
    - *IClient* will be renamed to *Connector*.
    - *IServer* will be renamed to *Server*.
  - ClientDriver will be generated.
    - ```ServerConnector extends Connector```.
    - ```ClientDriver extends Connector```.
  - Do not override *Connector* or *ServerConnector*.
    - It will me a member of *IProtocol* typed classes.
    - *Communicator* shifts delivered message to its *listener: IProtocol*.
      - ```listener->replyData(invoke);```
      - https://github.com/samchon/framework/blob/master/ts/src/samchon/protocol/ServerConnector.ts#L33
    - <u>When web-socket is required</u>, then have a member *WebServerConnector* or *WebClientDriver*.
  - ExternalSystem do not use multiple inheritance.
    - *ExternalSystem* will extend *IProtocol*
    - *ExternalSystem* will have a member ```communicator: Communicator```

Ordinary design who forced inheritance has a great weakness when protocol is changed, especially web-socket. When I want to make a web-socket based parallel processsing system, then have to inherit ordinary parallel module's class and it certainly requires **multiple and virtual inheritances**. However, following your design with separation of network communication function from basic class (*IProtocol*), the problem is solved.


#### Pseudo Code
Basic components of network communication will be newly reformed like below:

``` cpp
// ABSTRACT, YOUR COMMUNICATION
class Communicator : public IProtocol
{
protected:
	IProtocol *listener;
	std::shared_ptr<Socket> socekt;

public:
	Communicator(IProtocol *listener, std::shared_ptr<Socket> socket = null);
	virtual ~Communicator();

	virtual void listen();
	
	virtual void sendData(std::shared_ptr<Invoke>) override; // ORDINARY IClient::sendData() is kept
	virtual void replyData(std::shared_ptr<Invoke>) override; // CALLS listener->replyData()
};

class ServerConnector : public Commmunication
{
public:
	ServerConnector(IProtocol *listener);
	virtual ~ServerConnector();

	// Communicator::socket is constructed in here.
	virtual void connect(const std::string &ip, int port, const std::string &my_ip = "");
};

// YOUR IDEAN, CLIENT_DRIVER
class ClientDriver : public Communication
{
protected:
	ClientDriver(IProtocol *listener, std::shared_ptr<Socket> socket);
	virtual ~ClientDriver();
};
```

External System class, who is the basic class of distributed and parallel processing system will be reformed like below. From now on, to specify network role and protocol (normal or web-socket) of *ExternalSystem*, only overriding *createCommunicator()* is required.

```cpp
// ABSTRACT, SOME SIBLINGS ARE SERVERS AND SOME ARE CLIENTS
class ExternalSystem : public IProtocol
{
protected:
	std::shared_ptr<Communicator> communicator;
	
	// SPECIFY ITS TYPE, SERVER OR CLEINT? 
	// 	new ClientDriver() or new ServerConnector() ?
	virtual auto createCommunicator() -> Communicator* = 0;
}
```


#### Thanks for your sugguestion
In past time, I'd designed basic components of network communication with such ideas:
  - If an object inherited *ServerConnector* who inherited *IClient*, then it's the **real client**.
  - Otherwise, only inherited *IClient*, it's the **client driver**.
  - All of network classes acting communication (as a client, or with client) is a type of the **IClient**.

However, when implementing web socket classes, those principles cannot be kept.
In Web-socket, server and client have different message protocol. So I had made those classes.

My Idea  | Your Sugguestion
------------|---------------------------
IWebClientBase | ICommunication
IWebClientDriver | IClientDriver
WebServerConnector | -

* https://github.com/samchon/framework/blob/39c1e7f3b39c0ff196800d41012f058c69d4882a/cpp/samchon/protocol/IWebClient.hpp

Aren't they seem like your sugguestion? However, at that time, I couldn't realize and grasp the solution. Implementing the web-socket classes, I couldn't approach to the answer. However, by your sugguestion, now, I can approach to the solution and catch it. I could not only improve efficiency but also solve the **incompatibility** problem with JavaScript. 

I really appreciate for your idea. Thanks for you sugguestion.

**Comment by taeguk** [comment]
Thank you for your great interest in my suggestion.
My suggestion is a just draft, not a detail.
Detail design and class names depend on your judgment.
I just hope that the samchon framework moves in the better direction.
And if there is what I can do for it, I'm willing to help you.
